### ISSUE TITLE
Update and docker image

### ISSUE THREAD

**Issue by Koratsuki** [jniltinho/smb4manager#14]
Can be possible to update this repo to Ubuntu 20.04/22.04/24.04 and add Dockerfile?

Thanks in advance.

**Comment by jniltinho** [comment]
@Koratsuki 

Yes, I added the Dockerfile, now you need to test the application and make it work, at the moment I don't have time to validate this part, feel free to do these tests.

**Comment by jniltinho** [comment]
See this project https://github.com/jniltinho/go-samba4

**Comment by Koratsuki** [comment]
Tested and doesn't work. How can I contact you and send/show you my tests?
